Name=input("what is your name")
print(Name)
Grade=input("Which grade are you in")
print(Grade)
science=input('what is your Science score')
print(science)
maths=input('what is your Maths score')
print(maths)
English=input("what is your english score")
print(English)
SocialStudies=input("What is your Social Studies score")
print(SocialStudies)
Computerscience=input("What is your ComputerScience score")
print(Computerscience)
Totalscore=input("what is the total score")
print(Totalscore)